// Canonical mapping between TypeScript domain fields (camelCase) and Postgres
// columns (snake_case), plus generic row<->entity converters. Every Supabase
// api module uses this so the mapping lives in exactly one place. (This replaces
// the private M[] table inside data/backend.ts, which Part D removes.)

export interface TableMap {
  table: string
  fields: Record<string, string> // tsField -> db_column
  numeric: string[] // tsFields that must be coerced to Number on read
}

export const maps = {
  companies: {
    table: 'companies',
    numeric: [],
    fields: {
      id: 'id',
      code: 'code',
      name: 'name',
      contactPerson: 'contact_person',
      phone: 'phone',
      email: 'email',
      billingAddress: 'billing_address',
      gstin: 'gstin',
      active: 'active',
      notes: 'notes',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  materials: {
    table: 'materials',
    numeric: ['defaultRate', 'reorderLevel'],
    fields: {
      id: 'id',
      code: 'code',
      name: 'name',
      companyId: 'company_id',
      type: 'type',
      unit: 'unit',
      description: 'description',
      defaultRate: 'default_rate',
      reorderLevel: 'reorder_level',
      active: 'active',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  products: {
    table: 'products',
    numeric: ['rate'],
    fields: {
      id: 'id',
      code: 'code',
      name: 'name',
      rate: 'rate',
      unit: 'unit',
      hsn: 'hsn',
      active: 'active',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  jobs: {
    table: 'job_orders',
    numeric: ['orderedQty', 'completedQty', 'rejectedQty', 'rate'],
    fields: {
      id: 'id',
      jobNo: 'job_no',
      companyId: 'company_id',
      customerPo: 'customer_po',
      partName: 'part_name',
      partNumber: 'part_number',
      materialId: 'material_id',
      orderedQty: 'ordered_qty',
      completedQty: 'completed_qty',
      rejectedQty: 'rejected_qty',
      rate: 'rate',
      orderDate: 'order_date',
      dueDate: 'due_date',
      priority: 'priority',
      status: 'status',
      notes: 'notes',
      startedAt: 'started_at',
      completedAt: 'completed_at',
      deliveredAt: 'delivered_at',
      operator: 'operator',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  productionEvents: {
    table: 'production_events',
    numeric: ['completedQty'],
    fields: {
      id: 'id',
      jobId: 'job_id',
      type: 'type',
      fromStatus: 'from_status',
      toStatus: 'to_status',
      completedQty: 'completed_qty',
      note: 'note',
      operator: 'operator',
      at: 'at',
    },
  },
  receipts: {
    table: 'material_receipts',
    numeric: ['quantity', 'rate'],
    fields: {
      id: 'id',
      receiptNo: 'receipt_no',
      date: 'date',
      materialId: 'material_id',
      ownerType: 'owner_type',
      companyId: 'company_id',
      jobId: 'job_id',
      supplier: 'supplier',
      quantity: 'quantity',
      unit: 'unit',
      rate: 'rate',
      batchNo: 'batch_no',
      reference: 'reference',
      notes: 'notes',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  issues: {
    table: 'material_issues',
    numeric: ['quantity'],
    fields: {
      id: 'id',
      issueNo: 'issue_no',
      date: 'date',
      materialId: 'material_id',
      jobId: 'job_id',
      companyId: 'company_id',
      quantity: 'quantity',
      unit: 'unit',
      note: 'note',
      sourceReceiptId: 'source_receipt_id',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  adjustments: {
    table: 'stock_adjustments',
    numeric: ['quantity'],
    fields: {
      id: 'id',
      adjNo: 'adj_no',
      date: 'date',
      materialId: 'material_id',
      companyId: 'company_id',
      quantity: 'quantity',
      unit: 'unit',
      reason: 'reason',
      sourceReceiptId: 'source_receipt_id',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  deliveryChallans: {
    table: 'delivery_challans',
    numeric: [],
    fields: {
      id: 'id',
      dcNo: 'dc_no',
      date: 'date',
      companyId: 'company_id',
      jobId: 'job_id',
      reference: 'reference',
      vehicleNo: 'vehicle_no',
      lines: 'lines',
      notes: 'notes',
      status: 'status',
      invoiceId: 'invoice_id',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  invoices: {
    table: 'invoices',
    numeric: ['discount', 'taxPercent', 'cgstPercent', 'sgstPercent'],
    fields: {
      id: 'id',
      invoiceNo: 'invoice_no',
      date: 'date',
      companyId: 'company_id',
      billingAddress: 'billing_address',
      shippingAddress: 'shipping_address',
      reference: 'reference',
      dcReference: 'dc_reference',
      discount: 'discount',
      taxPercent: 'tax_percent',
      cgstPercent: 'cgst_percent',
      sgstPercent: 'sgst_percent',
      status: 'status',
      notes: 'notes',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  payments: {
    table: 'payments',
    numeric: ['amount'],
    fields: {
      id: 'id',
      paymentNo: 'payment_no',
      date: 'date',
      companyId: 'company_id',
      invoiceId: 'invoice_id',
      amount: 'amount',
      method: 'method',
      reference: 'reference',
      isAdvance: 'is_advance',
      notes: 'notes',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  expenses: {
    table: 'expenses',
    numeric: ['amount'],
    fields: {
      id: 'id',
      expenseNo: 'expense_no',
      date: 'date',
      category: 'category',
      amount: 'amount',
      method: 'method',
      vendor: 'vendor',
      reference: 'reference',
      companyId: 'company_id',
      jobId: 'job_id',
      notes: 'notes',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  auditLog: {
    table: 'audit_log',
    numeric: [],
    fields: {
      id: 'id',
      at: 'at',
      entity: 'entity',
      entityId: 'entity_id',
      action: 'action',
      summary: 'summary',
      actor: 'actor',
    },
  },
  ownPurchases: {
    table: 'own_material_purchases',
    numeric: ['quantity', 'totalCost', 'totalGst', 'totalAmount'],
    fields: {
      id: 'id',
      supplier: 'supplier',
      materialId: 'material_id',
      purchaseDate: 'purchase_date',
      quantity: 'quantity',
      unit: 'unit',
      totalCost: 'total_cost',
      totalGst: 'total_gst',
      totalAmount: 'total_amount',
      notes: 'notes',
      receiptId: 'receipt_id',
      expenseId: 'expense_id',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  materialReceiptStock: {
    table: 'material_receipt_stock',
    numeric: [
      'received',
      'dcQty',
      'invoiceQty',
      'otherOut',
      'totalDispatched',
      'adjusted',
      'available',
    ],
    fields: {
      receiptId: 'receipt_id',
      receiptNo: 'receipt_no',
      date: 'date',
      materialId: 'material_id',
      companyId: 'company_id',
      ownerType: 'owner_type',
      ownership: 'ownership',
      sourceDocNo: 'source_doc_no',
      supplier: 'supplier',
      unit: 'unit',
      received: 'received',
      dcQty: 'dc_qty',
      invoiceQty: 'invoice_qty',
      otherOut: 'other_out',
      totalDispatched: 'total_dispatched',
      adjusted: 'adjusted',
      available: 'available',
      status: 'status',
    },
  },
  inventoryLedger: {
    table: 'inventory_ledger',
    numeric: ['qtyIn', 'qtyOut'],
    fields: {
      id: 'id',
      materialId: 'material_id',
      companyId: 'company_id',
      ownership: 'ownership',
      txnType: 'txn_type',
      qtyIn: 'qty_in',
      qtyOut: 'qty_out',
      unit: 'unit',
      date: 'date',
      docNo: 'doc_no',
      referenceType: 'reference_type',
      referenceId: 'reference_id',
      note: 'note',
      createdAt: 'created_at',
    },
  },
  vendors: {
    table: 'vendors',
    numeric: [],
    fields: {
      id: 'id',
      code: 'code',
      name: 'name',
      gstin: 'gstin',
      phone: 'phone',
      email: 'email',
      address: 'address',
      active: 'active',
      notes: 'notes',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  subcontractOrders: {
    table: 'subcontract_orders',
    numeric: ['sentQty', 'receivedQty', 'rejectedQty'],
    fields: {
      id: 'id',
      scNo: 'sc_no',
      date: 'date',
      vendorId: 'vendor_id',
      materialId: 'material_id',
      ownerType: 'owner_type',
      companyId: 'company_id',
      jobId: 'job_id',
      process: 'process',
      unit: 'unit',
      sentQty: 'sent_qty',
      receivedQty: 'received_qty',
      rejectedQty: 'rejected_qty',
      status: 'status',
      notes: 'notes',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  subcontractDocs: {
    table: 'subcontract_docs',
    numeric: ['quantity', 'rejected', 'amount'],
    fields: {
      id: 'id',
      docNo: 'doc_no',
      scId: 'sc_id',
      direction: 'direction',
      docKind: 'doc_kind',
      vendorRef: 'vendor_ref',
      date: 'date',
      quantity: 'quantity',
      rejected: 'rejected',
      unit: 'unit',
      amount: 'amount',
      expenseId: 'expense_id',
      notes: 'notes',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  // ---- HRM ----------------------------------------------------------------
  departments: {
    table: 'departments',
    numeric: [],
    fields: {
      id: 'id',
      companyId: 'company_id',
      code: 'code',
      name: 'name',
      description: 'description',
      parentId: 'parent_id',
      headEmployeeId: 'head_employee_id',
      active: 'active',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  designations: {
    table: 'designations',
    numeric: [],
    fields: {
      id: 'id',
      companyId: 'company_id',
      code: 'code',
      name: 'name',
      departmentId: 'department_id',
      grade: 'grade',
      description: 'description',
      active: 'active',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  employees: {
    table: 'employees',
    numeric: ['probationMonths', 'noticePeriodDays'],
    fields: {
      id: 'id',
      companyId: 'company_id',
      employeeCode: 'employee_code',
      firstName: 'first_name',
      middleName: 'middle_name',
      lastName: 'last_name',
      displayName: 'display_name',
      photoUrl: 'photo_url',
      gender: 'gender',
      dateOfBirth: 'date_of_birth',
      nationality: 'nationality',
      maritalStatus: 'marital_status',
      personalEmail: 'personal_email',
      workEmail: 'work_email',
      mobile: 'mobile',
      alternateMobile: 'alternate_mobile',
      addressLine: 'address_line',
      city: 'city',
      state: 'state',
      country: 'country',
      postalCode: 'postal_code',
      emergencyName: 'emergency_name',
      emergencyRelation: 'emergency_relation',
      emergencyPhone: 'emergency_phone',
      dateOfJoining: 'date_of_joining',
      employmentType: 'employment_type',
      departmentId: 'department_id',
      designationId: 'designation_id',
      reportingManagerId: 'reporting_manager_id',
      location: 'location',
      branch: 'branch',
      workLocation: 'work_location',
      shiftId: 'shift_id',
      status: 'status',
      confirmationDate: 'confirmation_date',
      probationMonths: 'probation_months',
      noticePeriodDays: 'notice_period_days',
      dateOfLeaving: 'date_of_leaving',
      reasonForLeaving: 'reason_for_leaving',
      bankAccountNo: 'bank_account_no',
      bankName: 'bank_name',
      bankIfsc: 'bank_ifsc',
      bankAccountHolder: 'bank_account_holder',
      paymentMethod: 'payment_method',
      statutory: 'statutory',
      notes: 'notes',
      archivedAt: 'archived_at',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
      createdBy: 'created_by',
    },
  },
  shifts: {
    table: 'shifts',
    numeric: [
      'breakMinutes',
      'graceMinutes',
      'lateAfterMinutes',
      'earlyExitMinutes',
      'otAfterMinutes',
    ],
    fields: {
      id: 'id',
      companyId: 'company_id',
      code: 'code',
      name: 'name',
      startTime: 'start_time',
      endTime: 'end_time',
      breakMinutes: 'break_minutes',
      graceMinutes: 'grace_minutes',
      lateAfterMinutes: 'late_after_minutes',
      earlyExitMinutes: 'early_exit_minutes',
      otAfterMinutes: 'ot_after_minutes',
      workingDays: 'working_days',
      isOvernight: 'is_overnight',
      active: 'active',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  holidays: {
    table: 'holidays',
    numeric: [],
    fields: {
      id: 'id',
      companyId: 'company_id',
      name: 'name',
      holidayDate: 'holiday_date',
      type: 'type',
      location: 'location',
      departmentId: 'department_id',
      active: 'active',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  leaveTypes: {
    table: 'leave_types',
    numeric: ['annualQuota', 'maxCarryForward'],
    fields: {
      id: 'id',
      companyId: 'company_id',
      code: 'code',
      name: 'name',
      isPaid: 'is_paid',
      annualQuota: 'annual_quota',
      accrual: 'accrual',
      carryForward: 'carry_forward',
      maxCarryForward: 'max_carry_forward',
      allowHalfDay: 'allow_half_day',
      allowNegative: 'allow_negative',
      probationEligible: 'probation_eligible',
      requiresHrApproval: 'requires_hr_approval',
      color: 'color',
      active: 'active',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  leaveBalances: {
    table: 'leave_balances',
    numeric: ['year', 'opening', 'accrued', 'used', 'pending', 'adjusted'],
    fields: {
      id: 'id',
      employeeId: 'employee_id',
      leaveTypeId: 'leave_type_id',
      year: 'year',
      opening: 'opening',
      accrued: 'accrued',
      used: 'used',
      pending: 'pending',
      adjusted: 'adjusted',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  leaveApplications: {
    table: 'leave_applications',
    numeric: ['days'],
    fields: {
      id: 'id',
      companyId: 'company_id',
      employeeId: 'employee_id',
      leaveTypeId: 'leave_type_id',
      startDate: 'start_date',
      endDate: 'end_date',
      isHalfDay: 'is_half_day',
      halfDayPart: 'half_day_part',
      days: 'days',
      reason: 'reason',
      attachmentUrl: 'attachment_url',
      status: 'status',
      managerId: 'manager_id',
      decidedBy: 'decided_by',
      decidedAt: 'decided_at',
      decisionNote: 'decision_note',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  attendance: {
    table: 'attendance',
    numeric: ['totalMinutes', 'regularMinutes', 'overtimeMinutes'],
    fields: {
      id: 'id',
      companyId: 'company_id',
      employeeId: 'employee_id',
      attendanceDate: 'attendance_date',
      shiftId: 'shift_id',
      checkIn: 'check_in',
      checkOut: 'check_out',
      totalMinutes: 'total_minutes',
      regularMinutes: 'regular_minutes',
      overtimeMinutes: 'overtime_minutes',
      status: 'status',
      source: 'source',
      remarks: 'remarks',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
      createdBy: 'created_by',
    },
  },
  salaryComponents: {
    table: 'salary_components',
    numeric: ['sort'],
    fields: {
      id: 'id',
      companyId: 'company_id',
      code: 'code',
      name: 'name',
      kind: 'kind',
      calcType: 'calc_type',
      isStatutory: 'is_statutory',
      taxable: 'taxable',
      sort: 'sort',
      active: 'active',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  salaryStructures: {
    table: 'salary_structures',
    numeric: [],
    fields: {
      id: 'id',
      companyId: 'company_id',
      name: 'name',
      description: 'description',
      active: 'active',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  employeeSalary: {
    table: 'employee_salary',
    numeric: ['ctc'],
    fields: {
      id: 'id',
      employeeId: 'employee_id',
      structureId: 'structure_id',
      ctc: 'ctc',
      effectiveFrom: 'effective_from',
      effectiveTo: 'effective_to',
      createdAt: 'created_at',
      createdBy: 'created_by',
    },
  },
  payrollPeriods: {
    table: 'payroll_periods',
    numeric: [],
    fields: {
      id: 'id',
      companyId: 'company_id',
      name: 'name',
      startDate: 'start_date',
      endDate: 'end_date',
      payDate: 'pay_date',
      status: 'status',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  payrollRuns: {
    table: 'payroll_runs',
    numeric: ['employeeCount', 'grossTotal', 'deductionTotal', 'netTotal'],
    fields: {
      id: 'id',
      periodId: 'period_id',
      companyId: 'company_id',
      status: 'status',
      runAt: 'run_at',
      runBy: 'run_by',
      employeeCount: 'employee_count',
      grossTotal: 'gross_total',
      deductionTotal: 'deduction_total',
      netTotal: 'net_total',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  payrollRecords: {
    table: 'payroll_records',
    numeric: ['gross', 'totalDeductions', 'net', 'paidDays', 'lopDays'],
    fields: {
      id: 'id',
      runId: 'run_id',
      periodId: 'period_id',
      employeeId: 'employee_id',
      gross: 'gross',
      totalDeductions: 'total_deductions',
      net: 'net',
      paidDays: 'paid_days',
      lopDays: 'lop_days',
      earnings: 'earnings',
      deductions: 'deductions',
      createdAt: 'created_at',
    },
  },
  documentTypes: {
    table: 'document_types',
    numeric: [],
    fields: {
      id: 'id',
      companyId: 'company_id',
      code: 'code',
      name: 'name',
      hasExpiry: 'has_expiry',
      active: 'active',
      createdAt: 'created_at',
    },
  },
  employeeDocuments: {
    table: 'employee_documents',
    numeric: [],
    fields: {
      id: 'id',
      companyId: 'company_id',
      employeeId: 'employee_id',
      documentTypeId: 'document_type_id',
      title: 'title',
      documentNo: 'document_no',
      issueDate: 'issue_date',
      expiryDate: 'expiry_date',
      filePath: 'file_path',
      status: 'status',
      remarks: 'remarks',
      createdAt: 'created_at',
      createdBy: 'created_by',
    },
  },
  employeeAssets: {
    table: 'employee_assets',
    numeric: [],
    fields: {
      id: 'id',
      companyId: 'company_id',
      code: 'code',
      name: 'name',
      category: 'category',
      serialNo: 'serial_no',
      status: 'status',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  assetAssignments: {
    table: 'asset_assignments',
    numeric: [],
    fields: {
      id: 'id',
      assetId: 'asset_id',
      employeeId: 'employee_id',
      assignedDate: 'assigned_date',
      conditionOut: 'condition_out',
      expectedReturn: 'expected_return',
      returnedDate: 'returned_date',
      conditionIn: 'condition_in',
      remarks: 'remarks',
      createdAt: 'created_at',
    },
  },
  employeeAdvances: {
    table: 'employee_advances',
    numeric: ['amount', 'installments', 'outstanding'],
    fields: {
      id: 'id',
      companyId: 'company_id',
      employeeId: 'employee_id',
      amount: 'amount',
      reason: 'reason',
      advanceDate: 'advance_date',
      installments: 'installments',
      outstanding: 'outstanding',
      status: 'status',
      approvedBy: 'approved_by',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  expenseCategories: {
    table: 'expense_categories',
    numeric: [],
    fields: {
      id: 'id',
      companyId: 'company_id',
      code: 'code',
      name: 'name',
      active: 'active',
      createdAt: 'created_at',
    },
  },
  expenseClaims: {
    table: 'expense_claims',
    numeric: ['amount'],
    fields: {
      id: 'id',
      companyId: 'company_id',
      employeeId: 'employee_id',
      categoryId: 'category_id',
      amount: 'amount',
      claimDate: 'claim_date',
      description: 'description',
      receiptPath: 'receipt_path',
      status: 'status',
      approver: 'approver',
      decidedAt: 'decided_at',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  jobOpenings: {
    table: 'job_openings',
    numeric: ['openings'],
    fields: {
      id: 'id',
      companyId: 'company_id',
      title: 'title',
      departmentId: 'department_id',
      designationId: 'designation_id',
      location: 'location',
      employmentType: 'employment_type',
      openings: 'openings',
      description: 'description',
      requirements: 'requirements',
      status: 'status',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  candidates: {
    table: 'candidates',
    numeric: ['rating'],
    fields: {
      id: 'id',
      companyId: 'company_id',
      jobId: 'job_id',
      name: 'name',
      email: 'email',
      phone: 'phone',
      resumePath: 'resume_path',
      source: 'source',
      stage: 'stage',
      rating: 'rating',
      notes: 'notes',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  interviewRounds: {
    table: 'interview_rounds',
    numeric: ['roundNo', 'rating'],
    fields: {
      id: 'id',
      candidateId: 'candidate_id',
      roundNo: 'round_no',
      interviewer: 'interviewer',
      scheduledAt: 'scheduled_at',
      mode: 'mode',
      status: 'status',
      rating: 'rating',
      feedback: 'feedback',
      decision: 'decision',
      createdAt: 'created_at',
    },
  },
  performanceCycles: {
    table: 'performance_cycles',
    numeric: ['ratingScale'],
    fields: {
      id: 'id',
      companyId: 'company_id',
      name: 'name',
      startDate: 'start_date',
      endDate: 'end_date',
      ratingScale: 'rating_scale',
      status: 'status',
      createdAt: 'created_at',
    },
  },
  performanceReviews: {
    table: 'performance_reviews',
    numeric: ['selfRating', 'managerRating', 'finalRating'],
    fields: {
      id: 'id',
      cycleId: 'cycle_id',
      employeeId: 'employee_id',
      reviewerId: 'reviewer_id',
      selfRating: 'self_rating',
      managerRating: 'manager_rating',
      finalRating: 'final_rating',
      status: 'status',
      comments: 'comments',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  trainingPrograms: {
    table: 'training_programs',
    numeric: [],
    fields: {
      id: 'id',
      companyId: 'company_id',
      code: 'code',
      name: 'name',
      category: 'category',
      description: 'description',
      active: 'active',
      createdAt: 'created_at',
    },
  },
  trainingSessions: {
    table: 'training_sessions',
    numeric: ['durationHours'],
    fields: {
      id: 'id',
      programId: 'program_id',
      trainer: 'trainer',
      startDate: 'start_date',
      endDate: 'end_date',
      durationHours: 'duration_hours',
      location: 'location',
      status: 'status',
      createdAt: 'created_at',
    },
  },
  employeeTraining: {
    table: 'employee_training',
    numeric: [],
    fields: {
      id: 'id',
      sessionId: 'session_id',
      employeeId: 'employee_id',
      status: 'status',
      completionDate: 'completion_date',
      certificatePath: 'certificate_path',
      createdAt: 'created_at',
    },
  },
} satisfies Record<string, TableMap>

export type Row = Record<string, unknown>

// DB row -> TS entity. null -> undefined; numeric strings -> Number.
export function fromRow<T>(row: Row, map: TableMap): T {
  const obj: Record<string, unknown> = {}
  for (const [tsField, col] of Object.entries(map.fields)) {
    let v = row[col]
    if (v === null) v = undefined
    else if (map.numeric.includes(tsField) && v !== undefined) v = Number(v)
    obj[tsField] = v
  }
  return obj as T
}

// TS entity -> DB row. undefined -> null (so columns are explicitly cleared).
export function toRow(entity: Record<string, unknown>, map: TableMap): Row {
  const row: Row = {}
  for (const [tsField, col] of Object.entries(map.fields)) {
    const v = entity[tsField]
    row[col] = v === undefined ? null : v
  }
  return row
}
