// Canonical mapping between TypeScript domain fields (camelCase) and Postgres
// columns (snake_case), plus generic row<->entity converters. Every Supabase
// api module uses this so the mapping lives in exactly one place. (This replaces
// the private M[] table inside data/backend.ts, which Part D removes.)

export interface TableMap {
  table: string
  fields: Record<string, string> // tsField -> db_column
  numeric: string[] // tsFields that must be coerced to Number on read
}

export const maps = {
  companies: {
    table: 'companies',
    numeric: [],
    fields: {
      id: 'id',
      code: 'code',
      name: 'name',
      contactPerson: 'contact_person',
      phone: 'phone',
      email: 'email',
      billingAddress: 'billing_address',
      gstin: 'gstin',
      active: 'active',
      notes: 'notes',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  materials: {
    table: 'materials',
    numeric: ['defaultRate', 'reorderLevel'],
    fields: {
      id: 'id',
      code: 'code',
      name: 'name',
      companyId: 'company_id',
      type: 'type',
      unit: 'unit',
      description: 'description',
      defaultRate: 'default_rate',
      reorderLevel: 'reorder_level',
      active: 'active',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  products: {
    table: 'products',
    numeric: ['rate'],
    fields: {
      id: 'id',
      code: 'code',
      name: 'name',
      rate: 'rate',
      unit: 'unit',
      hsn: 'hsn',
      active: 'active',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  jobs: {
    table: 'job_orders',
    numeric: ['orderedQty', 'completedQty', 'rejectedQty', 'rate'],
    fields: {
      id: 'id',
      jobNo: 'job_no',
      companyId: 'company_id',
      customerPo: 'customer_po',
      partName: 'part_name',
      partNumber: 'part_number',
      materialId: 'material_id',
      orderedQty: 'ordered_qty',
      completedQty: 'completed_qty',
      rejectedQty: 'rejected_qty',
      rate: 'rate',
      orderDate: 'order_date',
      dueDate: 'due_date',
      priority: 'priority',
      status: 'status',
      notes: 'notes',
      startedAt: 'started_at',
      completedAt: 'completed_at',
      deliveredAt: 'delivered_at',
      operator: 'operator',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  productionEvents: {
    table: 'production_events',
    numeric: ['completedQty'],
    fields: {
      id: 'id',
      jobId: 'job_id',
      type: 'type',
      fromStatus: 'from_status',
      toStatus: 'to_status',
      completedQty: 'completed_qty',
      note: 'note',
      operator: 'operator',
      at: 'at',
    },
  },
  receipts: {
    table: 'material_receipts',
    numeric: ['quantity', 'rate'],
    fields: {
      id: 'id',
      receiptNo: 'receipt_no',
      date: 'date',
      materialId: 'material_id',
      ownerType: 'owner_type',
      companyId: 'company_id',
      jobId: 'job_id',
      supplier: 'supplier',
      quantity: 'quantity',
      unit: 'unit',
      rate: 'rate',
      batchNo: 'batch_no',
      reference: 'reference',
      notes: 'notes',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  issues: {
    table: 'material_issues',
    numeric: ['quantity'],
    fields: {
      id: 'id',
      issueNo: 'issue_no',
      date: 'date',
      materialId: 'material_id',
      jobId: 'job_id',
      companyId: 'company_id',
      quantity: 'quantity',
      unit: 'unit',
      note: 'note',
      sourceReceiptId: 'source_receipt_id',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  adjustments: {
    table: 'stock_adjustments',
    numeric: ['quantity'],
    fields: {
      id: 'id',
      adjNo: 'adj_no',
      date: 'date',
      materialId: 'material_id',
      companyId: 'company_id',
      quantity: 'quantity',
      unit: 'unit',
      reason: 'reason',
      sourceReceiptId: 'source_receipt_id',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  deliveryChallans: {
    table: 'delivery_challans',
    numeric: [],
    fields: {
      id: 'id',
      dcNo: 'dc_no',
      date: 'date',
      companyId: 'company_id',
      jobId: 'job_id',
      reference: 'reference',
      vehicleNo: 'vehicle_no',
      lines: 'lines',
      notes: 'notes',
      status: 'status',
      invoiceId: 'invoice_id',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  invoices: {
    table: 'invoices',
    numeric: ['discount', 'taxPercent', 'cgstPercent', 'sgstPercent'],
    fields: {
      id: 'id',
      invoiceNo: 'invoice_no',
      date: 'date',
      companyId: 'company_id',
      billingAddress: 'billing_address',
      shippingAddress: 'shipping_address',
      reference: 'reference',
      dcReference: 'dc_reference',
      discount: 'discount',
      taxPercent: 'tax_percent',
      cgstPercent: 'cgst_percent',
      sgstPercent: 'sgst_percent',
      status: 'status',
      notes: 'notes',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  payments: {
    table: 'payments',
    numeric: ['amount'],
    fields: {
      id: 'id',
      paymentNo: 'payment_no',
      date: 'date',
      companyId: 'company_id',
      invoiceId: 'invoice_id',
      amount: 'amount',
      method: 'method',
      reference: 'reference',
      isAdvance: 'is_advance',
      notes: 'notes',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  expenses: {
    table: 'expenses',
    numeric: ['amount'],
    fields: {
      id: 'id',
      expenseNo: 'expense_no',
      date: 'date',
      category: 'category',
      amount: 'amount',
      method: 'method',
      vendor: 'vendor',
      payee: 'payee',
      reference: 'reference',
      companyId: 'company_id',
      jobId: 'job_id',
      notes: 'notes',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  auditLog: {
    table: 'audit_log',
    numeric: [],
    fields: {
      id: 'id',
      at: 'at',
      entity: 'entity',
      entityId: 'entity_id',
      action: 'action',
      summary: 'summary',
      actor: 'actor',
    },
  },
  ownPurchases: {
    table: 'own_material_purchases',
    numeric: ['quantity', 'totalCost', 'totalGst', 'totalAmount'],
    fields: {
      id: 'id',
      supplier: 'supplier',
      materialId: 'material_id',
      purchaseDate: 'purchase_date',
      quantity: 'quantity',
      unit: 'unit',
      totalCost: 'total_cost',
      totalGst: 'total_gst',
      totalAmount: 'total_amount',
      notes: 'notes',
      receiptId: 'receipt_id',
      expenseId: 'expense_id',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  materialReceiptStock: {
    table: 'material_receipt_stock',
    numeric: [
      'received',
      'dcQty',
      'invoiceQty',
      'otherOut',
      'totalDispatched',
      'adjusted',
      'available',
    ],
    fields: {
      receiptId: 'receipt_id',
      receiptNo: 'receipt_no',
      date: 'date',
      materialId: 'material_id',
      companyId: 'company_id',
      ownerType: 'owner_type',
      ownership: 'ownership',
      sourceDocNo: 'source_doc_no',
      supplier: 'supplier',
      unit: 'unit',
      received: 'received',
      dcQty: 'dc_qty',
      invoiceQty: 'invoice_qty',
      otherOut: 'other_out',
      totalDispatched: 'total_dispatched',
      adjusted: 'adjusted',
      available: 'available',
      status: 'status',
    },
  },
  inventoryLedger: {
    table: 'inventory_ledger',
    numeric: ['qtyIn', 'qtyOut'],
    fields: {
      id: 'id',
      materialId: 'material_id',
      companyId: 'company_id',
      ownership: 'ownership',
      txnType: 'txn_type',
      qtyIn: 'qty_in',
      qtyOut: 'qty_out',
      unit: 'unit',
      date: 'date',
      docNo: 'doc_no',
      referenceType: 'reference_type',
      referenceId: 'reference_id',
      note: 'note',
      createdAt: 'created_at',
    },
  },
  vendors: {
    table: 'vendors',
    numeric: [],
    fields: {
      id: 'id',
      code: 'code',
      name: 'name',
      gstin: 'gstin',
      phone: 'phone',
      email: 'email',
      address: 'address',
      active: 'active',
      notes: 'notes',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  subcontractOrders: {
    table: 'subcontract_orders',
    numeric: ['sentQty', 'receivedQty', 'rejectedQty'],
    fields: {
      id: 'id',
      scNo: 'sc_no',
      date: 'date',
      vendorId: 'vendor_id',
      materialId: 'material_id',
      ownerType: 'owner_type',
      companyId: 'company_id',
      jobId: 'job_id',
      process: 'process',
      unit: 'unit',
      sentQty: 'sent_qty',
      receivedQty: 'received_qty',
      rejectedQty: 'rejected_qty',
      status: 'status',
      notes: 'notes',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  subcontractDocs: {
    table: 'subcontract_docs',
    numeric: ['quantity', 'rejected', 'amount'],
    fields: {
      id: 'id',
      docNo: 'doc_no',
      scId: 'sc_id',
      direction: 'direction',
      docKind: 'doc_kind',
      vendorRef: 'vendor_ref',
      date: 'date',
      quantity: 'quantity',
      rejected: 'rejected',
      unit: 'unit',
      amount: 'amount',
      expenseId: 'expense_id',
      notes: 'notes',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  // ---- HRM ----------------------------------------------------------------
  departments: {
    table: 'departments',
    numeric: [],
    fields: {
      id: 'id',
      companyId: 'company_id',
      code: 'code',
      name: 'name',
      description: 'description',
      parentId: 'parent_id',
      headEmployeeId: 'head_employee_id',
      active: 'active',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  designations: {
    table: 'designations',
    numeric: [],
    fields: {
      id: 'id',
      companyId: 'company_id',
      code: 'code',
      name: 'name',
      departmentId: 'department_id',
      grade: 'grade',
      description: 'description',
      active: 'active',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  employees: {
    table: 'employees',
    numeric: ['probationMonths', 'noticePeriodDays'],
    fields: {
      id: 'id',
      companyId: 'company_id',
      employeeCode: 'employee_code',
      firstName: 'first_name',
      middleName: 'middle_name',
      lastName: 'last_name',
      displayName: 'display_name',
      photoUrl: 'photo_url',
      gender: 'gender',
      dateOfBirth: 'date_of_birth',
      nationality: 'nationality',
      maritalStatus: 'marital_status',
      personalEmail: 'personal_email',
      workEmail: 'work_email',
      mobile: 'mobile',
      alternateMobile: 'alternate_mobile',
      addressLine: 'address_line',
      city: 'city',
      state: 'state',
      country: 'country',
      postalCode: 'postal_code',
      emergencyName: 'emergency_name',
      emergencyRelation: 'emergency_relation',
      emergencyPhone: 'emergency_phone',
      dateOfJoining: 'date_of_joining',
      employmentType: 'employment_type',
      departmentId: 'department_id',
      designationId: 'designation_id',
      reportingManagerId: 'reporting_manager_id',
      location: 'location',
      branch: 'branch',
      workLocation: 'work_location',
      shiftId: 'shift_id',
      status: 'status',
      confirmationDate: 'confirmation_date',
      probationMonths: 'probation_months',
      noticePeriodDays: 'notice_period_days',
      dateOfLeaving: 'date_of_leaving',
      reasonForLeaving: 'reason_for_leaving',
      bankAccountNo: 'bank_account_no',
      bankName: 'bank_name',
      bankIfsc: 'bank_ifsc',
      bankAccountHolder: 'bank_account_holder',
      paymentMethod: 'payment_method',
      statutory: 'statutory',
      notes: 'notes',
      archivedAt: 'archived_at',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
      createdBy: 'created_by',
    },
  },
  shifts: {
    table: 'shifts',
    numeric: [
      'breakMinutes',
      'graceMinutes',
      'lateAfterMinutes',
      'earlyExitMinutes',
      'otAfterMinutes',
    ],
    fields: {
      id: 'id',
      companyId: 'company_id',
      code: 'code',
      name: 'name',
      startTime: 'start_time',
      endTime: 'end_time',
      breakMinutes: 'break_minutes',
      graceMinutes: 'grace_minutes',
      lateAfterMinutes: 'late_after_minutes',
      earlyExitMinutes: 'early_exit_minutes',
      otAfterMinutes: 'ot_after_minutes',
      workingDays: 'working_days',
      isOvernight: 'is_overnight',
      active: 'active',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  holidays: {
    table: 'holidays',
    numeric: [],
    fields: {
      id: 'id',
      companyId: 'company_id',
      name: 'name',
      holidayDate: 'holiday_date',
      type: 'type',
      location: 'location',
      departmentId: 'department_id',
      active: 'active',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  leaveTypes: {
    table: 'leave_types',
    numeric: ['annualQuota', 'maxCarryForward'],
    fields: {
      id: 'id',
      companyId: 'company_id',
      code: 'code',
      name: 'name',
      isPaid: 'is_paid',
      annualQuota: 'annual_quota',
      accrual: 'accrual',
      carryForward: 'carry_forward',
      maxCarryForward: 'max_carry_forward',
      allowHalfDay: 'allow_half_day',
      allowNegative: 'allow_negative',
      probationEligible: 'probation_eligible',
      requiresHrApproval: 'requires_hr_approval',
      color: 'color',
      active: 'active',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  leaveBalances: {
    table: 'leave_balances',
    numeric: ['year', 'opening', 'accrued', 'used', 'pending', 'adjusted'],
    fields: {
      id: 'id',
      employeeId: 'employee_id',
      leaveTypeId: 'leave_type_id',
      year: 'year',
      opening: 'opening',
      accrued: 'accrued',
      used: 'used',
      pending: 'pending',
      adjusted: 'adjusted',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  leaveApplications: {
    table: 'leave_applications',
    numeric: ['days'],
    fields: {
      id: 'id',
      companyId: 'company_id',
      employeeId: 'employee_id',
      leaveTypeId: 'leave_type_id',
      startDate: 'start_date',
      endDate: 'end_date',
      isHalfDay: 'is_half_day',
      halfDayPart: 'half_day_part',
      days: 'days',
      reason: 'reason',
      attachmentUrl: 'attachment_url',
      status: 'status',
      managerId: 'manager_id',
      decidedBy: 'decided_by',
      decidedAt: 'decided_at',
      decisionNote: 'decision_note',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  attendance: {
    table: 'attendance',
    numeric: ['totalMinutes', 'regularMinutes', 'overtimeMinutes'],
    fields: {
      id: 'id',
      companyId: 'company_id',
      employeeId: 'employee_id',
      attendanceDate: 'attendance_date',
      shiftId: 'shift_id',
      checkIn: 'check_in',
      checkOut: 'check_out',
      totalMinutes: 'total_minutes',
      regularMinutes: 'regular_minutes',
      overtimeMinutes: 'overtime_minutes',
      status: 'status',
      source: 'source',
      remarks: 'remarks',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
      createdBy: 'created_by',
    },
  },
  salaryComponents: {
    table: 'salary_components',
    numeric: ['sort'],
    fields: {
      id: 'id',
      companyId: 'company_id',
      code: 'code',
      name: 'name',
      kind: 'kind',
      calcType: 'calc_type',
      isStatutory: 'is_statutory',
      taxable: 'taxable',
      sort: 'sort',
      active: 'active',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  salaryStructures: {
    table: 'salary_structures',
    numeric: [],
    fields: {
      id: 'id',
      companyId: 'company_id',
      name: 'name',
      description: 'description',
      active: 'active',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  employeeSalary: {
    table: 'employee_salary',
    numeric: ['ctc'],
    fields: {
      id: 'id',
      employeeId: 'employee_id',
      structureId: 'structure_id',
      ctc: 'ctc',
      effectiveFrom: 'effective_from',
      effectiveTo: 'effective_to',
      createdAt: 'created_at',
      createdBy: 'created_by',
    },
  },
  payrollPeriods: {
    table: 'payroll_periods',
    numeric: [],
    fields: {
      id: 'id',
      companyId: 'company_id',
      name: 'name',
      startDate: 'start_date',
      endDate: 'end_date',
      payDate: 'pay_date',
      status: 'status',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  payrollRuns: {
    table: 'payroll_runs',
    numeric: ['employeeCount', 'grossTotal', 'deductionTotal', 'netTotal'],
    fields: {
      id: 'id',
      periodId: 'period_id',
      companyId: 'company_id',
      status: 'status',
      runAt: 'run_at',
      runBy: 'run_by',
      employeeCount: 'employee_count',
      grossTotal: 'gross_total',
      deductionTotal: 'deduction_total',
      netTotal: 'net_total',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  payrollRecords: {
    table: 'payroll_records',
    numeric: ['gross', 'totalDeductions', 'net', 'paidDays', 'lopDays'],
    fields: {
      id: 'id',
      runId: 'run_id',
      periodId: 'period_id',
      employeeId: 'employee_id',
      gross: 'gross',
      totalDeductions: 'total_deductions',
      net: 'net',
      paidDays: 'paid_days',
      lopDays: 'lop_days',
      earnings: 'earnings',
      deductions: 'deductions',
      createdAt: 'created_at',
    },
  },
  documentTypes: {
    table: 'document_types',
    numeric: [],
    fields: {
      id: 'id',
      companyId: 'company_id',
      code: 'code',
      name: 'name',
      hasExpiry: 'has_expiry',
      active: 'active',
      createdAt: 'created_at',
    },
  },
  employeeDocuments: {
    table: 'employee_documents',
    numeric: [],
    fields: {
      id: 'id',
      companyId: 'company_id',
      employeeId: 'employee_id',
      documentTypeId: 'document_type_id',
      title: 'title',
      documentNo: 'document_no',
      issueDate: 'issue_date',
      expiryDate: 'expiry_date',
      filePath: 'file_path',
      status: 'status',
      remarks: 'remarks',
      createdAt: 'created_at',
      createdBy: 'created_by',
    },
  },
  employeeAssets: {
    table: 'employee_assets',
    numeric: [],
    fields: {
      id: 'id',
      companyId: 'company_id',
      code: 'code',
      name: 'name',
      category: 'category',
      serialNo: 'serial_no',
      status: 'status',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  assetAssignments: {
    table: 'asset_assignments',
    numeric: [],
    fields: {
      id: 'id',
      assetId: 'asset_id',
      employeeId: 'employee_id',
      assignedDate: 'assigned_date',
      conditionOut: 'condition_out',
      expectedReturn: 'expected_return',
      returnedDate: 'returned_date',
      conditionIn: 'condition_in',
      remarks: 'remarks',
      createdAt: 'created_at',
    },
  },
  employeeAdvances: {
    table: 'employee_advances',
    numeric: ['amount', 'installments', 'outstanding'],
    fields: {
      id: 'id',
      companyId: 'company_id',
      employeeId: 'employee_id',
      amount: 'amount',
      reason: 'reason',
      advanceDate: 'advance_date',
      installments: 'installments',
      outstanding: 'outstanding',
      status: 'status',
      approvedBy: 'approved_by',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  expenseCategories: {
    table: 'expense_categories',
    numeric: [],
    fields: {
      id: 'id',
      companyId: 'company_id',
      code: 'code',
      name: 'name',
      active: 'active',
      createdAt: 'created_at',
    },
  },
  expenseClaims: {
    table: 'expense_claims',
    numeric: ['amount'],
    fields: {
      id: 'id',
      companyId: 'company_id',
      employeeId: 'employee_id',
      categoryId: 'category_id',
      amount: 'amount',
      claimDate: 'claim_date',
      description: 'description',
      receiptPath: 'receipt_path',
      status: 'status',
      approver: 'approver',
      decidedAt: 'decided_at',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  jobOpenings: {
    table: 'job_openings',
    numeric: ['openings'],
    fields: {
      id: 'id',
      companyId: 'company_id',
      title: 'title',
      departmentId: 'department_id',
      designationId: 'designation_id',
      location: 'location',
      employmentType: 'employment_type',
      openings: 'openings',
      description: 'description',
      requirements: 'requirements',
      status: 'status',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  candidates: {
    table: 'candidates',
    numeric: ['rating'],
    fields: {
      id: 'id',
      companyId: 'company_id',
      jobId: 'job_id',
      name: 'name',
      email: 'email',
      phone: 'phone',
      resumePath: 'resume_path',
      source: 'source',
      stage: 'stage',
      rating: 'rating',
      notes: 'notes',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  interviewRounds: {
    table: 'interview_rounds',
    numeric: ['roundNo', 'rating'],
    fields: {
      id: 'id',
      candidateId: 'candidate_id',
      roundNo: 'round_no',
      interviewer: 'interviewer',
      scheduledAt: 'scheduled_at',
      mode: 'mode',
      status: 'status',
      rating: 'rating',
      feedback: 'feedback',
      decision: 'decision',
      createdAt: 'created_at',
    },
  },
  performanceCycles: {
    table: 'performance_cycles',
    numeric: ['ratingScale'],
    fields: {
      id: 'id',
      companyId: 'company_id',
      name: 'name',
      startDate: 'start_date',
      endDate: 'end_date',
      ratingScale: 'rating_scale',
      status: 'status',
      createdAt: 'created_at',
    },
  },
  performanceReviews: {
    table: 'performance_reviews',
    numeric: ['selfRating', 'managerRating', 'finalRating'],
    fields: {
      id: 'id',
      cycleId: 'cycle_id',
      employeeId: 'employee_id',
      reviewerId: 'reviewer_id',
      selfRating: 'self_rating',
      managerRating: 'manager_rating',
      finalRating: 'final_rating',
      status: 'status',
      comments: 'comments',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  trainingPrograms: {
    table: 'training_programs',
    numeric: [],
    fields: {
      id: 'id',
      companyId: 'company_id',
      code: 'code',
      name: 'name',
      category: 'category',
      description: 'description',
      active: 'active',
      createdAt: 'created_at',
    },
  },
  trainingSessions: {
    table: 'training_sessions',
    numeric: ['durationHours'],
    fields: {
      id: 'id',
      programId: 'program_id',
      trainer: 'trainer',
      startDate: 'start_date',
      endDate: 'end_date',
      durationHours: 'duration_hours',
      location: 'location',
      status: 'status',
      createdAt: 'created_at',
    },
  },
  employeeTraining: {
    table: 'employee_training',
    numeric: [],
    fields: {
      id: 'id',
      sessionId: 'session_id',
      employeeId: 'employee_id',
      status: 'status',
      completionDate: 'completion_date',
      certificatePath: 'certificate_path',
      createdAt: 'created_at',
    },
  },
  // ---- Accounts & Finance -------------------------------------------------
  chartOfAccounts: {
    table: 'chart_of_accounts',
    numeric: ['openingBalance'],
    fields: {
      id: 'id',
      companyId: 'company_id',
      code: 'code',
      name: 'name',
      type: 'type',
      parentId: 'parent_id',
      isGroup: 'is_group',
      systemKey: 'system_key',
      gstRelevant: 'gst_relevant',
      openingBalance: 'opening_balance',
      active: 'active',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  fiscalYears: {
    table: 'fiscal_years',
    numeric: [],
    fields: {
      id: 'id',
      companyId: 'company_id',
      name: 'name',
      startDate: 'start_date',
      endDate: 'end_date',
      status: 'status',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  accountingPeriods: {
    table: 'accounting_periods',
    numeric: [],
    fields: {
      id: 'id',
      fiscalYearId: 'fiscal_year_id',
      companyId: 'company_id',
      name: 'name',
      startDate: 'start_date',
      endDate: 'end_date',
      status: 'status',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  journals: {
    table: 'journals',
    numeric: [],
    fields: {
      id: 'id',
      companyId: 'company_id',
      journalNo: 'journal_no',
      date: 'date',
      periodId: 'period_id',
      narration: 'narration',
      source: 'source',
      sourceType: 'source_type',
      sourceId: 'source_id',
      status: 'status',
      createdBy: 'created_by',
      postedBy: 'posted_by',
      postedAt: 'posted_at',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  journalLines: {
    table: 'journal_lines',
    numeric: ['debit', 'credit', 'lineNo'],
    fields: {
      id: 'id',
      journalId: 'journal_id',
      accountId: 'account_id',
      debit: 'debit',
      credit: 'credit',
      description: 'description',
      partyType: 'party_type',
      partyId: 'party_id',
      lineNo: 'line_no',
    },
  },
  bankAccounts: {
    table: 'bank_accounts',
    numeric: ['openingBalance'],
    fields: {
      id: 'id',
      companyId: 'company_id',
      name: 'name',
      bankName: 'bank_name',
      accountNumber: 'account_number',
      ifsc: 'ifsc',
      branch: 'branch',
      accountType: 'account_type',
      openingBalance: 'opening_balance',
      ledgerAccountId: 'ledger_account_id',
      active: 'active',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  bankStatementFiles: {
    table: 'bank_statement_files',
    numeric: ['fileSize', 'rowCount'],
    fields: {
      id: 'id',
      companyId: 'company_id',
      bankAccountId: 'bank_account_id',
      fileName: 'file_name',
      fileHash: 'file_hash',
      fileSize: 'file_size',
      parserType: 'parser_type',
      rowCount: 'row_count',
      status: 'status',
      meta: 'meta',
      importedBy: 'imported_by',
      importedAt: 'imported_at',
    },
  },
  bankTransactions: {
    table: 'bank_transactions',
    numeric: [
      'debitAmount',
      'creditAmount',
      'balanceAfter',
      'sourceRowNumber',
      'parserConfidence',
      'confidence',
    ],
    fields: {
      id: 'id',
      bankAccountId: 'bank_account_id',
      statementFileId: 'statement_file_id',
      companyId: 'company_id',
      transactionDate: 'transaction_date',
      valueDate: 'value_date',
      narration: 'narration',
      referenceNumber: 'reference_number',
      chequeNumber: 'cheque_number',
      debitAmount: 'debit_amount',
      creditAmount: 'credit_amount',
      balanceAfter: 'balance_after',
      currency: 'currency',
      sourceRowNumber: 'source_row_number',
      parserType: 'parser_type',
      parserConfidence: 'parser_confidence',
      classification: 'classification',
      matchedPartyType: 'matched_party_type',
      matchedPartyId: 'matched_party_id',
      matchedInvoiceId: 'matched_invoice_id',
      matchedLedgerAccountId: 'matched_ledger_account_id',
      confidence: 'confidence',
      dedupeHash: 'dedupe_hash',
      dupStatus: 'dup_status',
      reviewStatus: 'review_status',
      reconciliationStatus: 'reconciliation_status',
      postingStatus: 'posting_status',
      postedPaymentId: 'posted_payment_id',
      postedExpenseId: 'posted_expense_id',
      postedJournalId: 'posted_journal_id',
      notes: 'notes',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  bankTxnRules: {
    table: 'bank_txn_rules',
    numeric: ['priority', 'confidence'],
    fields: {
      id: 'id',
      companyId: 'company_id',
      name: 'name',
      priority: 'priority',
      matchField: 'match_field',
      matchOp: 'match_op',
      matchValue: 'match_value',
      direction: 'direction',
      classification: 'classification',
      partyType: 'party_type',
      partyId: 'party_id',
      ledgerAccountId: 'ledger_account_id',
      confidence: 'confidence',
      active: 'active',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  partyAliases: {
    table: 'party_aliases',
    numeric: [],
    fields: {
      id: 'id',
      companyId: 'company_id',
      partyType: 'party_type',
      partyId: 'party_id',
      alias: 'alias',
      createdAt: 'created_at',
    },
  },
  gstRegistrations: {
    table: 'gst_registrations',
    numeric: [],
    fields: {
      id: 'id',
      companyId: 'company_id',
      legalName: 'legal_name',
      tradeName: 'trade_name',
      gstin: 'gstin',
      registrationType: 'registration_type',
      state: 'state',
      stateCode: 'state_code',
      pan: 'pan',
      address: 'address',
      effectiveDate: 'effective_date',
      status: 'status',
      isDefault: 'is_default',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  gstTaxRates: {
    table: 'gst_tax_rates',
    numeric: ['totalRate', 'cgst', 'sgst', 'igst', 'cess'],
    fields: {
      id: 'id',
      name: 'name',
      totalRate: 'total_rate',
      cgst: 'cgst',
      sgst: 'sgst',
      igst: 'igst',
      cess: 'cess',
      active: 'active',
      createdAt: 'created_at',
    },
  },
  hsnCodes: {
    table: 'hsn_codes',
    numeric: [],
    fields: {
      id: 'id',
      code: 'code',
      kind: 'kind',
      description: 'description',
      taxRateId: 'tax_rate_id',
      unit: 'unit',
      active: 'active',
      createdAt: 'created_at',
    },
  },
  gstReturnPeriods: {
    table: 'gst_return_periods',
    numeric: [],
    fields: {
      id: 'id',
      companyId: 'company_id',
      gstin: 'gstin',
      period: 'period',
      returnType: 'return_type',
      status: 'status',
      summary: 'summary',
      preparedBy: 'prepared_by',
      preparedAt: 'prepared_at',
      filedAt: 'filed_at',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  einvoiceRecords: {
    table: 'einvoice_records',
    numeric: [],
    fields: {
      id: 'id',
      invoiceId: 'invoice_id',
      companyId: 'company_id',
      status: 'status',
      provider: 'provider',
      requestId: 'request_id',
      irn: 'irn',
      ackNo: 'ack_no',
      ackDate: 'ack_date',
      signedQr: 'signed_qr',
      qrData: 'qr_data',
      errorCode: 'error_code',
      errorMessage: 'error_message',
      cancelReason: 'cancel_reason',
      cancelledAt: 'cancelled_at',
      payload: 'payload',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  ewayBills: {
    table: 'eway_bills',
    numeric: ['taxableValue', 'invoiceValue', 'distanceKm'],
    fields: {
      id: 'id',
      invoiceId: 'invoice_id',
      companyId: 'company_id',
      ewbNumber: 'ewb_number',
      documentNo: 'document_no',
      documentType: 'document_type',
      documentDate: 'document_date',
      supplierGstin: 'supplier_gstin',
      recipientGstin: 'recipient_gstin',
      fromAddress: 'from_address',
      toAddress: 'to_address',
      fromPincode: 'from_pincode',
      toPincode: 'to_pincode',
      items: 'items',
      taxableValue: 'taxable_value',
      invoiceValue: 'invoice_value',
      transporterId: 'transporter_id',
      transporterName: 'transporter_name',
      transportMode: 'transport_mode',
      vehicleNumber: 'vehicle_number',
      transportDocNumber: 'transport_doc_number',
      transportDocDate: 'transport_doc_date',
      distanceKm: 'distance_km',
      generatedDate: 'generated_date',
      validUntil: 'valid_until',
      status: 'status',
      cancellationDate: 'cancellation_date',
      provider: 'provider',
      responseMeta: 'response_meta',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  // ---- Inventory (Stock Transfers) ----------------------------------------
  stockTransfers: {
    table: 'stock_transfers',
    numeric: ['quantity'],
    fields: {
      id: 'id',
      transferNo: 'transfer_no',
      materialId: 'material_id',
      companyId: 'company_id',
      fromLocation: 'from_location',
      toLocation: 'to_location',
      quantity: 'quantity',
      unit: 'unit',
      transferDate: 'transfer_date',
      requestedBy: 'requested_by',
      approvedBy: 'approved_by',
      status: 'status',
      remarks: 'remarks',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
      createdBy: 'created_by',
    },
  },
  // ---- Tool Room ----------------------------------------------------------
  toolCategories: {
    table: 'tool_categories',
    numeric: [],
    fields: {
      id: 'id',
      code: 'code',
      name: 'name',
      description: 'description',
      parentId: 'parent_id',
      active: 'active',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  tools: {
    table: 'tools',
    numeric: [
      'minStock',
      'maxStock',
      'reorderLevel',
      'reorderQty',
      'safetyStock',
      'expectedLife',
      'unitCost',
      'calibrationFrequencyDays',
      'maintenanceFrequencyDays',
    ],
    fields: {
      id: 'id',
      code: 'code',
      name: 'name',
      categoryId: 'category_id',
      subCategory: 'sub_category',
      classification: 'classification',
      toolType: 'tool_type',
      description: 'description',
      manufacturer: 'manufacturer',
      brand: 'brand',
      modelNumber: 'model_number',
      partNumber: 'part_number',
      oemNumber: 'oem_number',
      serialNumber: 'serial_number',
      specification: 'specification',
      size: 'size',
      dimension: 'dimension',
      material: 'material',
      grade: 'grade',
      standard: 'standard',
      uom: 'uom',
      minStock: 'min_stock',
      maxStock: 'max_stock',
      reorderLevel: 'reorder_level',
      reorderQty: 'reorder_qty',
      safetyStock: 'safety_stock',
      binLocation: 'bin_location',
      rack: 'rack',
      shelf: 'shelf',
      storeLocation: 'store_location',
      warehouse: 'warehouse',
      toolRoomLocation: 'tool_room_location',
      purchaseDate: 'purchase_date',
      expectedLife: 'expected_life',
      lifeUnit: 'life_unit',
      replacementFrequency: 'replacement_frequency',
      currentCondition: 'current_condition',
      unitCost: 'unit_cost',
      isSerialized: 'is_serialized',
      isBatchControlled: 'is_batch_controlled',
      isLotControlled: 'is_lot_controlled',
      calibrationRequired: 'calibration_required',
      calibrationFrequencyDays: 'calibration_frequency_days',
      maintenanceRequired: 'maintenance_required',
      maintenanceFrequencyDays: 'maintenance_frequency_days',
      inspectionRequired: 'inspection_required',
      returnRequired: 'return_required',
      isConsumable: 'is_consumable',
      status: 'status',
      notes: 'notes',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
      createdBy: 'created_by',
    },
  },
  toolTransactions: {
    table: 'tool_transactions',
    numeric: ['qty', 'unitCost'],
    fields: {
      id: 'id',
      txnNo: 'txn_no',
      toolId: 'tool_id',
      txnType: 'txn_type',
      qty: 'qty',
      fromBucket: 'from_bucket',
      toBucket: 'to_bucket',
      unit: 'unit',
      unitCost: 'unit_cost',
      locationFrom: 'location_from',
      locationTo: 'location_to',
      jobId: 'job_id',
      machine: 'machine',
      operation: 'operation',
      employee: 'employee',
      department: 'department',
      purpose: 'purpose',
      condition: 'condition',
      reservationId: 'reservation_id',
      maintenanceId: 'maintenance_id',
      calibrationId: 'calibration_id',
      serialNumber: 'serial_number',
      batchNo: 'batch_no',
      refType: 'ref_type',
      refId: 'ref_id',
      refNo: 'ref_no',
      refKey: 'ref_key',
      note: 'note',
      actorEmail: 'actor_email',
      at: 'at',
    },
  },
  // Read-only aggregated view (never written directly).
  toolInventory: {
    table: 'tool_inventory',
    numeric: [
      'minStock',
      'reorderLevel',
      'availableQty',
      'reservedQty',
      'issuedQty',
      'maintenanceQty',
      'calibrationQty',
      'damagedQty',
      'scrapQty',
      'consumedQty',
      'onHandQty',
      'netQty',
    ],
    fields: {
      toolId: 'tool_id',
      code: 'code',
      name: 'name',
      categoryId: 'category_id',
      brand: 'brand',
      partNumber: 'part_number',
      serialNumber: 'serial_number',
      uom: 'uom',
      storeLocation: 'store_location',
      warehouse: 'warehouse',
      toolRoomLocation: 'tool_room_location',
      binLocation: 'bin_location',
      minStock: 'min_stock',
      reorderLevel: 'reorder_level',
      isConsumable: 'is_consumable',
      toolStatus: 'tool_status',
      availableQty: 'available_qty',
      reservedQty: 'reserved_qty',
      issuedQty: 'issued_qty',
      maintenanceQty: 'maintenance_qty',
      calibrationQty: 'calibration_qty',
      damagedQty: 'damaged_qty',
      scrapQty: 'scrap_qty',
      consumedQty: 'consumed_qty',
      onHandQty: 'on_hand_qty',
      netQty: 'net_qty',
      isOutOfStock: 'is_out_of_stock',
      isLowStock: 'is_low_stock',
    },
  },
  toolReservations: {
    table: 'tool_reservations',
    numeric: ['qty', 'issuedQty'],
    fields: {
      id: 'id',
      reservationNo: 'reservation_no',
      toolId: 'tool_id',
      qty: 'qty',
      issuedQty: 'issued_qty',
      requiredDate: 'required_date',
      jobId: 'job_id',
      machine: 'machine',
      operation: 'operation',
      employee: 'employee',
      reservedBy: 'reserved_by',
      status: 'status',
      notes: 'notes',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  toolMaintenance: {
    table: 'tool_maintenance',
    numeric: ['qty', 'cost'],
    fields: {
      id: 'id',
      maintenanceNo: 'maintenance_no',
      toolId: 'tool_id',
      qty: 'qty',
      serialNumber: 'serial_number',
      maintenanceType: 'maintenance_type',
      maintenanceDate: 'maintenance_date',
      dueDate: 'due_date',
      serviceProvider: 'service_provider',
      technician: 'technician',
      cost: 'cost',
      partsUsed: 'parts_used',
      description: 'description',
      result: 'result',
      condition: 'condition',
      nextDueDate: 'next_due_date',
      status: 'status',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
  toolCalibrations: {
    table: 'tool_calibrations',
    numeric: ['qty'],
    fields: {
      id: 'id',
      calibrationNo: 'calibration_no',
      toolId: 'tool_id',
      qty: 'qty',
      serialNumber: 'serial_number',
      calibrationDate: 'calibration_date',
      dueDate: 'due_date',
      agency: 'agency',
      certificateNo: 'certificate_no',
      result: 'result',
      accuracy: 'accuracy',
      tolerance: 'tolerance',
      status: 'status',
      certificatePath: 'certificate_path',
      remarks: 'remarks',
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  },
} satisfies Record<string, TableMap>

export type Row = Record<string, unknown>

// DB row -> TS entity. null -> undefined; numeric strings -> Number.
export function fromRow<T>(row: Row, map: TableMap): T {
  const obj: Record<string, unknown> = {}
  for (const [tsField, col] of Object.entries(map.fields)) {
    let v = row[col]
    if (v === null) v = undefined
    else if (map.numeric.includes(tsField) && v !== undefined) v = Number(v)
    obj[tsField] = v
  }
  return obj as T
}

// TS entity -> DB row. undefined -> null (so columns are explicitly cleared).
export function toRow(entity: Record<string, unknown>, map: TableMap): Row {
  const row: Row = {}
  for (const [tsField, col] of Object.entries(map.fields)) {
    const v = entity[tsField]
    row[col] = v === undefined ? null : v
  }
  return row
}
