/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAccountsRouteImport } from './routes/app/accounts'
import { Route as AppApprovalsRouteImport } from './routes/app/approvals'
import { Route as AppCompaniesRouteImport } from './routes/app/companies'
import { Route as AppConfigurationRouteImport } from './routes/app/configuration'
import { Route as AppExpensesRouteImport } from './routes/app/expenses'
import { Route as AppJobsRouteImport } from './routes/app/jobs'
import { Route as AppMaterialsRouteImport } from './routes/app/materials'
import { Route as AppPaymentsRouteImport } from './routes/app/payments'
import { Route as AppProductionRouteImport } from './routes/app/production'
import { Route as AppProductionPlanningRouteImport } from './routes/app/production-planning'
import { Route as AppReportsRouteImport } from './routes/app/reports'
import { Route as AppSalesRouteImport } from './routes/app/sales'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppSubcontractingRouteImport } from './routes/app/subcontracting'
import { Route as AppSupplyChainRouteImport } from './routes/app/supply-chain'
import { Route as AppVendorsRouteImport } from './routes/app/vendors'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AppDeliveriesIndexRouteImport } from './routes/app/deliveries/index'
import { Route as AppInvoicesIndexRouteImport } from './routes/app/invoices/index'
import { Route as AppDeliveriesIdPrintRouteImport } from './routes/app/deliveries/$id.print'
import { Route as AppInvoicesIdPrintRouteImport } from './routes/app/invoices/$id.print'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCompaniesRoute = AppCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppConfigurationRoute = AppConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMaterialsRoute = AppMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductionRoute = AppProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductionPlanningRoute = AppProductionPlanningRouteImport.update({
  id: '/production-planning',
  path: '/production-planning',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSubcontractingRoute = AppSubcontractingRouteImport.update({
  id: '/subcontracting',
  path: '/subcontracting',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSupplyChainRoute = AppSupplyChainRouteImport.update({
  id: '/supply-chain',
  path: '/supply-chain',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVendorsRoute = AppVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AppRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDeliveriesIndexRoute = AppDeliveriesIndexRouteImport.update({
  id: '/deliveries/',
  path: '/deliveries/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDeliveriesIdPrintRoute = AppDeliveriesIdPrintRouteImport.update({
  id: '/deliveries/$id/print',
  path: '/deliveries/$id/print',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInvoicesIdPrintRoute = AppInvoicesIdPrintRouteImport.update({
  id: '/invoices/$id/print',
  path: '/invoices/$id/print',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/configuration': typeof AppConfigurationRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/materials': typeof AppMaterialsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/production': typeof AppProductionRoute
  '/app/production-planning': typeof AppProductionPlanningRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sales': typeof AppSalesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subcontracting': typeof AppSubcontractingRoute
  '/app/supply-chain': typeof AppSupplyChainRoute
  '/app/vendors': typeof AppVendorsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/app/deliveries/': typeof AppDeliveriesIndexRoute
  '/app/invoices/': typeof AppInvoicesIndexRoute
  '/app/deliveries/$id/print': typeof AppDeliveriesIdPrintRoute
  '/app/invoices/$id/print': typeof AppInvoicesIdPrintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/configuration': typeof AppConfigurationRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/materials': typeof AppMaterialsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/production': typeof AppProductionRoute
  '/app/production-planning': typeof AppProductionPlanningRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sales': typeof AppSalesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subcontracting': typeof AppSubcontractingRoute
  '/app/supply-chain': typeof AppSupplyChainRoute
  '/app/vendors': typeof AppVendorsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/app': typeof AppIndexRoute
  '/blog': typeof BlogIndexRoute
  '/app/deliveries': typeof AppDeliveriesIndexRoute
  '/app/invoices': typeof AppInvoicesIndexRoute
  '/app/deliveries/$id/print': typeof AppDeliveriesIdPrintRoute
  '/app/invoices/$id/print': typeof AppInvoicesIdPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/configuration': typeof AppConfigurationRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/materials': typeof AppMaterialsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/production': typeof AppProductionRoute
  '/app/production-planning': typeof AppProductionPlanningRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sales': typeof AppSalesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subcontracting': typeof AppSubcontractingRoute
  '/app/supply-chain': typeof AppSupplyChainRoute
  '/app/vendors': typeof AppVendorsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/app/deliveries/': typeof AppDeliveriesIndexRoute
  '/app/invoices/': typeof AppInvoicesIndexRoute
  '/app/deliveries/$id/print': typeof AppDeliveriesIdPrintRoute
  '/app/invoices/$id/print': typeof AppInvoicesIdPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/accounts'
    | '/app/approvals'
    | '/app/companies'
    | '/app/configuration'
    | '/app/expenses'
    | '/app/jobs'
    | '/app/materials'
    | '/app/payments'
    | '/app/production'
    | '/app/production-planning'
    | '/app/reports'
    | '/app/sales'
    | '/app/settings'
    | '/app/subcontracting'
    | '/app/supply-chain'
    | '/app/vendors'
    | '/blog/$slug'
    | '/app/'
    | '/blog/'
    | '/app/deliveries/'
    | '/app/invoices/'
    | '/app/deliveries/$id/print'
    | '/app/invoices/$id/print'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/accounts'
    | '/app/approvals'
    | '/app/companies'
    | '/app/configuration'
    | '/app/expenses'
    | '/app/jobs'
    | '/app/materials'
    | '/app/payments'
    | '/app/production'
    | '/app/production-planning'
    | '/app/reports'
    | '/app/sales'
    | '/app/settings'
    | '/app/subcontracting'
    | '/app/supply-chain'
    | '/app/vendors'
    | '/blog/$slug'
    | '/app'
    | '/blog'
    | '/app/deliveries'
    | '/app/invoices'
    | '/app/deliveries/$id/print'
    | '/app/invoices/$id/print'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/accounts'
    | '/app/approvals'
    | '/app/companies'
    | '/app/configuration'
    | '/app/expenses'
    | '/app/jobs'
    | '/app/materials'
    | '/app/payments'
    | '/app/production'
    | '/app/production-planning'
    | '/app/reports'
    | '/app/sales'
    | '/app/settings'
    | '/app/subcontracting'
    | '/app/supply-chain'
    | '/app/vendors'
    | '/blog/$slug'
    | '/app/'
    | '/blog/'
    | '/app/deliveries/'
    | '/app/invoices/'
    | '/app/deliveries/$id/print'
    | '/app/invoices/$id/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/accounts': {
      id: '/app/accounts'
      path: '/accounts'
      fullPath: '/app/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/approvals': {
      id: '/app/approvals'
      path: '/approvals'
      fullPath: '/app/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/companies': {
      id: '/app/companies'
      path: '/companies'
      fullPath: '/app/companies'
      preLoaderRoute: typeof AppCompaniesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/configuration': {
      id: '/app/configuration'
      path: '/configuration'
      fullPath: '/app/configuration'
      preLoaderRoute: typeof AppConfigurationRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/expenses': {
      id: '/app/expenses'
      path: '/expenses'
      fullPath: '/app/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/jobs': {
      id: '/app/jobs'
      path: '/jobs'
      fullPath: '/app/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/materials': {
      id: '/app/materials'
      path: '/materials'
      fullPath: '/app/materials'
      preLoaderRoute: typeof AppMaterialsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/production': {
      id: '/app/production'
      path: '/production'
      fullPath: '/app/production'
      preLoaderRoute: typeof AppProductionRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/production-planning': {
      id: '/app/production-planning'
      path: '/production-planning'
      fullPath: '/app/production-planning'
      preLoaderRoute: typeof AppProductionPlanningRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/sales': {
      id: '/app/sales'
      path: '/sales'
      fullPath: '/app/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/subcontracting': {
      id: '/app/subcontracting'
      path: '/subcontracting'
      fullPath: '/app/subcontracting'
      preLoaderRoute: typeof AppSubcontractingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/supply-chain': {
      id: '/app/supply-chain'
      path: '/supply-chain'
      fullPath: '/app/supply-chain'
      preLoaderRoute: typeof AppSupplyChainRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/vendors': {
      id: '/app/vendors'
      path: '/vendors'
      fullPath: '/app/vendors'
      preLoaderRoute: typeof AppVendorsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/deliveries/': {
      id: '/app/deliveries/'
      path: '/deliveries'
      fullPath: '/app/deliveries/'
      preLoaderRoute: typeof AppDeliveriesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/invoices/': {
      id: '/app/invoices/'
      path: '/invoices'
      fullPath: '/app/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/deliveries/$id/print': {
      id: '/app/deliveries/$id/print'
      path: '/deliveries/$id/print'
      fullPath: '/app/deliveries/$id/print'
      preLoaderRoute: typeof AppDeliveriesIdPrintRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/invoices/$id/print': {
      id: '/app/invoices/$id/print'
      path: '/invoices/$id/print'
      fullPath: '/app/invoices/$id/print'
      preLoaderRoute: typeof AppInvoicesIdPrintRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppCompaniesRoute: typeof AppCompaniesRoute
  AppConfigurationRoute: typeof AppConfigurationRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppJobsRoute: typeof AppJobsRoute
  AppMaterialsRoute: typeof AppMaterialsRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppProductionRoute: typeof AppProductionRoute
  AppProductionPlanningRoute: typeof AppProductionPlanningRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubcontractingRoute: typeof AppSubcontractingRoute
  AppSupplyChainRoute: typeof AppSupplyChainRoute
  AppVendorsRoute: typeof AppVendorsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDeliveriesIndexRoute: typeof AppDeliveriesIndexRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
  AppDeliveriesIdPrintRoute: typeof AppDeliveriesIdPrintRoute
  AppInvoicesIdPrintRoute: typeof AppInvoicesIdPrintRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppCompaniesRoute: AppCompaniesRoute,
  AppConfigurationRoute: AppConfigurationRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppJobsRoute: AppJobsRoute,
  AppMaterialsRoute: AppMaterialsRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppProductionRoute: AppProductionRoute,
  AppProductionPlanningRoute: AppProductionPlanningRoute,
  AppReportsRoute: AppReportsRoute,
  AppSalesRoute: AppSalesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubcontractingRoute: AppSubcontractingRoute,
  AppSupplyChainRoute: AppSupplyChainRoute,
  AppVendorsRoute: AppVendorsRoute,
  AppIndexRoute: AppIndexRoute,
  AppDeliveriesIndexRoute: AppDeliveriesIndexRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
  AppDeliveriesIdPrintRoute: AppDeliveriesIdPrintRoute,
  AppInvoicesIdPrintRoute: AppInvoicesIdPrintRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
